// Generated by https://quicktype.io

class PhotoModel {
  int? id;
  int? sol;

  String? img_src;
  String? earth_date;

  PhotoModel({
    this.id,
    this.sol,
    this.img_src,
    this.earth_date,
  });

  factory PhotoModel.fromMap(Map<String, dynamic> map) {
    return PhotoModel(
      id: map['id'],
      earth_date: map['earth_date'],
      sol: map['sol'],
      img_src: map['img_src'],
    );
  }
}
/*
class Camera {
  int? id;
  String? name;
  int? roverId;
  String? fullName;

  Camera({
    this.id,
    this.name,
    this.roverId,
    this.fullName,
  });
}

class Rover {
  int? id;
  String? name;
  String? landingDate;
  String? launchDate;
  String? status;

  Rover({
    this.id,
    this.name,
    this.landingDate,
    this.launchDate,
    this.status,
  });
}
*/